### ISSUE TITLE
Signed distance of Line2

### ISSUE THREAD

**Issue by r4v3n6101** [cristicbz/rust-doom#147]
Analyzing different sources (wiki and wolfram math docs) I get information that signed distance is calculated as `n cross (point - origin)` and that conflicts with code implemented here: https://github.com/cristicbz/rust-doom/blob/2efa6aebdfb2c625e24188150357872f01f403ef/math/src/line.rs#L42
The question is this right or should be written as: 
`to.to_vec().perp_dot(self.displace) - self.origin.perp_dot(self.displace.to_vec())`

**Comment by M4SSD35TRUCT10N** [comment]
Does this conflict with original gameplay? Could be intentionally wrong. Seems that this repo is kinda abandoned, isn't it? Thinking of forking it, but currently I don't have much spare time.

**Comment by cristicbz** [comment]
Hey, no the repo is not abandoned, it's just in a state where I'm kinda happy with it. I've been thinking of replacing glium and the home brew ECS with bevy, to make it more maintainable for others as well.

I don't think the code is wrong, note that `displace` is not the normal, it's a displacement vector. I can double check when I'm at a computer though

**Comment by M4SSD35TRUCT10N** [comment]
Bevy would make it keep up with future enhancements for that matter I think - it's ultimately your choice. Would be nice if you could check that @cristicbz: "I don't think the code is wrong, note that displace is not the normal, it's a displacement vector. I can double check when I'm at a computer though.".

**Comment by r4v3n6101** [comment]
`displace` is kinda normal for plane but it's direction for line. Seems that Wikipedia was mistaken about this because WolframAlpha's formula is same as in this repo. I'll be glad if you double check this so I can understand your algorithm right. Thanks for anwser!

P.S. I'm trying to do my own rendering for doom's wad so I really appreciate you for your work, @cristicbz.
