### ISSUE TITLE
World should be stretched vertically by 20%

### ISSUE THREAD

**Issue by linguica** [cristicbz/rust-doom#36]
It looks like everything in the world is being drawn with texels of aspect ratio 1:1, which seems like the obvious thing to do. But Doom was designed to run in 320x200 (a 16:10 resolution) on a 4:3 (i.e. 16:12) monitor. This means that everything the game displayed was stretched vertically by 20% - the 1:1 texels are displayed as 5:6.

Here's an example. Doom as it's supposed to look:

![Normal Doom](http://doomwiki.org/w/images/c/c0/MAP01.png)

Doom as it looks in Doom95, which didn't take the stretching into account:

![Doom95](http://doomwiki.org/w/images/e/e2/Doom95-MAP01-Start.png)

More info on this quibble can be found at http://doomwiki.org/wiki/Aspect_ratio

**Comment by cristicbz** [comment]
Thanks a lot for the information, I thought it looked weird, but never knew why; such a simple fix makes such a big difference. +100 Doom Guru points to you. The fix is in #40, which I'll merge as soon as I hear from Travis.

**Comment by cristicbz** [comment]
I done messed up, #41 actually fixes it, will merge in a second.
