### ISSUE TITLE
Freedoom support

### ISSUE THREAD

**Issue by Calinou** [cristicbz/rust-doom#56]
How well is [Freedoom](http://freedoom.github.io/) supported? Note that I haven't tested, I'm just wondering.

**Comment by cristicbz** [comment]
Haven't tried, my focus has been on getting the originals running as well as possible. That said I'd be curious how it would work out. Feel free to give it a try and tell me what works and what doesn't and I'll be happy to fix stuff!

**Comment by cristicbz** [comment]
Just tried it, seems to work just fine!
