### ISSUE TITLE
Let Left/Right key rotate left/right instead of strafing

### ISSUE THREAD

**Issue by edward-san** [cristicbz/rust-doom#74]
Apparently, the only way to change the view angle is to use the mouse, but if it's disabled (via '`' key), there's no way to rotate with the keys.

**Comment by cristicbz** [comment]
Makes sense!

**Comment by cristicbz** [comment]
Very overdue, but I implemented this today! Sorry about that, real life and work have been super-hectic in the last 6 months or so.
