### ISSUE TITLE
cargo crate registry error: 'SDL' linked with two different versions.

### ISSUE THREAD

**Issue by edward-san** [cristicbz/rust-doom#77]
The whole message is (rust stable 1.5):

```
native library `SDL2` is being linked to by more than one package, and can only be linked to by one package

  sdl2-sys v0.7.0
  sdl2-sys v0.6.2
```

or (rust nightly 1.7):

```
native library `SDL2` is being linked to by more than one version of the same package, but it can only be linked once; try updating or pinning your dependencies to ensure that this package only shows up once

  sdl2-sys v0.7.0
  sdl2-sys v0.6.2
```

This can be reproduced by removing ```.cargo``` and rerunning ```cargo build``` on clean git tree. Then, the registry is updated, the crates are downloaded and then the message appears.

**Comment by cristicbz** [comment]
Huh, can reproduce. Looking into it now.

**Comment by cristicbz** [comment]
Created [PR](https://github.com/cristicbz/rust-doom/pull/78) to fix. `sdl2_ttf` and `sdl2` were bringing in different versions of `sdl2-sys`. Not sure how that happened despite the existence of a Cargo.lock file, but nevermind. I'll merge that once tests pass.

**Comment by cristicbz** [comment]
Hey @edward-san, thanks a lot for the issue! I think #78 should have fixed it, could you please try on your end and see if it's fixed?

**Comment by JIghtuse** [comment]
I just tried it before and after the commit. Works for me.

**Comment by edward-san** [comment]
It's fixed. Thanks!

**Comment by dallbee** [comment]
Looks like this is happening again. What can be done to keep the repos in sync?
