### ISSUE TITLE
Rare jumpy view rotation with left-right keyboard

### ISSUE THREAD

**Issue by edward-san** [cristicbz/rust-doom#86]
If in a map you rotate to the left/right, sometimes you see the view skip part of the rotation, so the view goes a little bit more rotated than it should.

**Comment by cristicbz** [comment]
Hmmm. I can't reproduce this, but I suspect it's caused by your computer dropping a couple of frames and my rudimentary framerate-independent maths ends up multiplying by too much.

I should probably do some kind of framerate smoothing or fixed timestep maths for the camera.

**Comment by cristicbz** [comment]
Don't think this happens anymore, feel free tor reopen if it does.
