### ISSUE TITLE
Build fails on OS X 10.11.4

### ISSUE THREAD

**Issue by lewisde** [cristicbz/rust-doom#87]
➜  Source git:(preview) brew install sdl2_ttf
Warning: sdl2_ttf-2.0.14 already installed

note: ld: library not found for -lSDL2_ttf
clang: error: linker command failed with exit code 1 (use -v to see invocation)

error: aborting due to previous error
error: Could not compile `rs_doom`.

➜  Source git:(preview) rustc --version
rustc 1.8.0

**Comment by cristicbz** [comment]
Weird! Can you run any rust program which uses sdl2_ttf ? Could you try the example on https://github.com/andelf/rust-sdl2_ttf ?

Thanks for the issue!

**Comment by lewisde** [comment]
Thanks for the link. That doesn't work either so I'll close this and investigate my end.
