### ISSUE TITLE
Game Crash when hitting any key

### ISSUE THREAD

**Issue by BearzRobotics** [cristicbz/rust-doom#94]
I just compiled the game and when I hit a key the game crashes.

target/release/rs_doom --iwad doom1.wad
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', /checkout/src/libcore/option.rs:335
stack backtrace:
   0: std::sys::imp::backtrace::tracing::imp::unwind_backtrace
             at /checkout/src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1: std::sys_common::backtrace::_print
             at /checkout/src/libstd/sys_common/backtrace.rs:71
   2: std::panicking::default_hook::{{closure}}
             at /checkout/src/libstd/sys_common/backtrace.rs:60
             at /checkout/src/libstd/panicking.rs:355
   3: std::panicking::default_hook
             at /checkout/src/libstd/panicking.rs:371
   4: std::panicking::rust_panic_with_hook
             at /checkout/src/libstd/panicking.rs:549
   5: std::panicking::begin_panic
             at /checkout/src/libstd/panicking.rs:511
   6: std::panicking::begin_panic_fmt
             at /checkout/src/libstd/panicking.rs:495
   7: rust_begin_unwind
             at /checkout/src/libstd/panicking.rs:471
   8: core::panicking::panic_fmt
             at /checkout/src/libcore/panicking.rs:71
   9: core::panicking::panic
             at /checkout/src/libcore/panicking.rs:51
  10: sdl2::event::Event::from_ll
  11: <sdl2::event::EventPollIterator<'a> as core::iter::iterator::Iterator>::next
  12: rs_doom::game::game::Game::run
  13: rs_doom::main
  14: __rust_maybe_catch_panic
             at /checkout/src/libpanic_unwind/lib.rs:98
  15: std::rt::lang_start
             at /checkout/src/libstd/panicking.rs:433
             at /checkout/src/libstd/panic.rs:361
             at /checkout/src/libstd/rt.rs:59
  16: __libc_start_main
  17: _start
             at ../sysdeps/x86_64/start.S:120
plex@plex ~/code/rust-doom $

**Comment by cristicbz** [comment]
Huh, I can repro this, sorry for the delay, I was travelling. The only explanation I've got is that the old version of sdl2-rust I'm using became incompatible with a newer version of SDL2.

Thanks for the report!

**Comment by cristicbz** [comment]
Ok @BearzRobotics I upgraded all the deps (including SDL2) to their newest versions and it seems to work now, have another go!

**Comment by BearzRobotics** [comment]
Thanks it works great now.
